// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getBaoMetrics
SEXP getBaoMetrics(SEXP sequences, SEXP indexes, SEXP types);
RcppExport SEXP _ORFhunteR_getBaoMetrics(SEXP sequencesSEXP, SEXP indexesSEXP, SEXP typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type types(typesSEXP);
    rcpp_result_gen = Rcpp::wrap(getBaoMetrics(sequences, indexes, types));
    return rcpp_result_gen;
END_RCPP
}
// getCorrelationFactors
SEXP getCorrelationFactors(SEXP string, SEXP pattern, SEXP blockSize);
RcppExport SEXP _ORFhunteR_getCorrelationFactors(SEXP stringSEXP, SEXP patternSEXP, SEXP blockSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type string(stringSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< SEXP >::type blockSize(blockSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(getCorrelationFactors(string, pattern, blockSize));
    return rcpp_result_gen;
END_RCPP
}
// getPatternCount_V
SEXP getPatternCount_V(SEXP string, SEXP pattern);
RcppExport SEXP _ORFhunteR_getPatternCount_V(SEXP stringSEXP, SEXP patternSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type string(stringSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pattern(patternSEXP);
    rcpp_result_gen = Rcpp::wrap(getPatternCount_V(string, pattern));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ORFhunteR_getBaoMetrics", (DL_FUNC) &_ORFhunteR_getBaoMetrics, 3},
    {"_ORFhunteR_getCorrelationFactors", (DL_FUNC) &_ORFhunteR_getCorrelationFactors, 3},
    {"_ORFhunteR_getPatternCount_V", (DL_FUNC) &_ORFhunteR_getPatternCount_V, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ORFhunteR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
