# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getBaoMetrics <- function(sequences, indexes, types) {
    .Call('_ORFhunteR_getBaoMetrics', PACKAGE = 'ORFhunteR', sequences, indexes, types)
}

getCorrelationFactors <- function(string, pattern, blockSize) {
    .Call('_ORFhunteR_getCorrelationFactors', PACKAGE = 'ORFhunteR', string, pattern, blockSize)
}

getPatternCount_V <- function(string, pattern) {
    .Call('_ORFhunteR_getPatternCount_V', PACKAGE = 'ORFhunteR', string, pattern)
}

